#############################################################################
# Makefile for building: bin/Analyzer
# Generated by qmake (2.01a) (Qt 4.6.0) on: ?? 1? 13 11:58:54 2010
# Project:  Analyzer.pro
# Template: app
# Command: /opt/qtsdk-2009.05/qt/bin/qmake -spec /opt/qtsdk-2009.05/qt/mkspecs/linux-g++ -unix -o Makefile Analyzer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qtsdk-2009.05/qt/mkspecs/linux-g++ -I. -I/opt/qtsdk-2009.05/qt/include/QtCore -I/opt/qtsdk-2009.05/qt/include/QtGui -I/opt/qtsdk-2009.05/qt/include -I../../dev/qwt-5.2.0/src -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qtsdk-2009.05/qt/lib
LIBS          = $(SUBLIBS)  -L/opt/qtsdk-2009.05/qt/lib /home/lihaibo/dev/qwt-5.2.0/lib/libqwt.a -lQtGui -L/opt/qtsdk-2009.05/qt/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qtsdk-2009.05/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		data_plot.cpp \
		mywidget.cpp \
		setdialog.cpp \
		pages.cpp moc_mainwindow.cpp \
		moc_data_plot.cpp \
		moc_mywidget.cpp \
		moc_setdialog.cpp \
		moc_pages.cpp \
		qrc_Analyzer.cpp
OBJECTS       = main.o \
		mainwindow.o \
		data_plot.o \
		mywidget.o \
		setdialog.o \
		pages.o \
		moc_mainwindow.o \
		moc_data_plot.o \
		moc_mywidget.o \
		moc_setdialog.o \
		moc_pages.o \
		qrc_Analyzer.o
DIST          = /opt/qtsdk-2009.05/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/release.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf \
		Analyzer.pro
QMAKE_TARGET  = Analyzer
DESTDIR       = bin/
TARGET        = bin/Analyzer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Analyzer.pro  /opt/qtsdk-2009.05/qt/mkspecs/linux-g++/qmake.conf /opt/qtsdk-2009.05/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/release.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf \
		/opt/qtsdk-2009.05/qt/lib/libQtGui.prl \
		/opt/qtsdk-2009.05/qt/lib/libQtCore.prl
	$(QMAKE) -spec /opt/qtsdk-2009.05/qt/mkspecs/linux-g++ -unix -o Makefile Analyzer.pro
/opt/qtsdk-2009.05/qt/mkspecs/common/g++.conf:
/opt/qtsdk-2009.05/qt/mkspecs/common/unix.conf:
/opt/qtsdk-2009.05/qt/mkspecs/common/linux.conf:
/opt/qtsdk-2009.05/qt/mkspecs/qconfig.pri:
/opt/qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/qt_config.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/default_pre.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/release.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/default_post.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/warn_on.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/qt.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/moc.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/resources.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/uic.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/yacc.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/lex.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf:
/opt/qtsdk-2009.05/qt/lib/libQtGui.prl:
/opt/qtsdk-2009.05/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qtsdk-2009.05/qt/mkspecs/linux-g++ -unix -o Makefile Analyzer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Analyzer1.0.0 || $(MKDIR) .tmp/Analyzer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Analyzer1.0.0/ && $(COPY_FILE) --parents mainwindow.h data_plot.h mywidget.h setdialog.h pages.h .tmp/Analyzer1.0.0/ && $(COPY_FILE) --parents Analyzer.qrc .tmp/Analyzer1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp data_plot.cpp mywidget.cpp setdialog.cpp pages.cpp .tmp/Analyzer1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/Analyzer1.0.0/ && (cd `dirname .tmp/Analyzer1.0.0` && $(TAR) Analyzer1.0.0.tar Analyzer1.0.0 && $(COMPRESS) Analyzer1.0.0.tar) && $(MOVE) `dirname .tmp/Analyzer1.0.0`/Analyzer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Analyzer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_data_plot.cpp moc_mywidget.cpp moc_setdialog.cpp moc_pages.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_data_plot.cpp moc_mywidget.cpp moc_setdialog.cpp moc_pages.cpp
moc_mainwindow.cpp: mywidget.h \
		data_plot.h \
		mainwindow.h
	/opt/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_data_plot.cpp: data_plot.h
	/opt/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) data_plot.h -o moc_data_plot.cpp

moc_mywidget.cpp: data_plot.h \
		mywidget.h
	/opt/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) mywidget.h -o moc_mywidget.cpp

moc_setdialog.cpp: setdialog.h
	/opt/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) setdialog.h -o moc_setdialog.cpp

moc_pages.cpp: pages.h
	/opt/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) pages.h -o moc_pages.cpp

compiler_rcc_make_all: qrc_Analyzer.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Analyzer.cpp
qrc_Analyzer.cpp: Analyzer.qrc \
		images/looknfeel.png \
		images/mydocuments.png
	/opt/qtsdk-2009.05/qt/bin/rcc -name Analyzer Analyzer.qrc -o qrc_Analyzer.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/opt/qtsdk-2009.05/qt/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		mywidget.h \
		data_plot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		mywidget.h \
		data_plot.h \
		ui_mainwindow.h \
		setdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

data_plot.o: data_plot.cpp data_plot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o data_plot.o data_plot.cpp

mywidget.o: mywidget.cpp mywidget.h \
		data_plot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mywidget.o mywidget.cpp

setdialog.o: setdialog.cpp setdialog.h \
		pages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setdialog.o setdialog.cpp

pages.o: pages.cpp pages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pages.o pages.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_data_plot.o: moc_data_plot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_data_plot.o moc_data_plot.cpp

moc_mywidget.o: moc_mywidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mywidget.o moc_mywidget.cpp

moc_setdialog.o: moc_setdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setdialog.o moc_setdialog.cpp

moc_pages.o: moc_pages.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pages.o moc_pages.cpp

qrc_Analyzer.o: qrc_Analyzer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Analyzer.o qrc_Analyzer.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

